spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testDB
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: INFO